<a href="https://colab.research.google.com/github/TheBottomOfTheDeepDarkOcean/AIO-Exercise/blob/develop/Module4/Module4_Tabular_Data_Project_Sales_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [152]:
import numpy as np
import matplotlib.pyplot as plt
import random
import pandas as pd

In [153]:
!gdown 1A8kK0IEsT3w8htzU18ihFr5UV-euhquC

Downloading...
From: https://drive.google.com/uc?id=1A8kK0IEsT3w8htzU18ihFr5UV-euhquC
To: /content/SalesPrediction.csv
100% 206k/206k [00:00<00:00, 36.7MB/s]


In [154]:
df = pd.read_csv('SalesPrediction.csv')

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   TV            4562 non-null   float64
 1   Radio         4568 non-null   float64
 2   Social Media  4566 non-null   float64
 3   Influencer    4572 non-null   object 
 4   Sales         4566 non-null   float64
dtypes: float64(4), object(1)
memory usage: 178.7+ KB


In [156]:
df.describe()

TV        Radio  Social Media        Sales
count  4562.000000  4568.000000   4566.000000  4566.000000
mean     54.066857    18.160356      3.323956   192.466602
std      26.125054     9.676958      2.212670    93.133092
min      10.000000     0.000684      0.000031    31.199409
25%      32.000000    10.525957      1.527849   112.322882
50%      53.000000    17.859513      3.055565   189.231172
75%      77.000000    25.649730      4.807558   272.507922
max     100.000000    48.871161     13.981662   364.079751

In [157]:
df.isnull().sum()

TV              10
Radio            4
Social Media     6
Influencer       0
Sales            6
dtype: int64

In [158]:
df

TV      Radio  Social Media Influencer       Sales
0     16.0   6.566231      2.907983       Mega   54.732757
1     13.0   9.237765      2.409567       Mega   46.677897
2     41.0  15.886446      2.913410       Mega  150.177829
3     83.0  30.020028      6.922304       Mega  298.246340
4     15.0   8.437408      1.405998      Micro   56.594181
...    ...        ...           ...        ...         ...
4567  26.0   4.472360      0.717090      Micro   94.685866
4568  71.0  20.610685      6.545573       Nano  249.101915
4569  44.0  19.800072      5.096192      Micro  163.631457
4570  71.0  17.534640      1.940873      Macro  253.610411
4571  42.0  15.966688      5.046548      Micro  148.202414

[4572 rows x 5 columns]

In [159]:
df = pd.get_dummies(df)

In [161]:
df

TV      Radio  Social Media       Sales  Influencer_Macro  \
0     16.0   6.566231      2.907983   54.732757             False   
1     13.0   9.237765      2.409567   46.677897             False   
2     41.0  15.886446      2.913410  150.177829             False   
3     83.0  30.020028      6.922304  298.246340             False   
4     15.0   8.437408      1.405998   56.594181             False   
...    ...        ...           ...         ...               ...   
4567  26.0   4.472360      0.717090   94.685866             False   
4568  71.0  20.610685      6.545573  249.101915             False   
4569  44.0  19.800072      5.096192  163.631457             False   
4570  71.0  17.534640      1.940873  253.610411              True   
4571  42.0  15.966688      5.046548  148.202414             False   

      Influencer_Mega  Influencer_Micro  Influencer_Nano  
0                True             False            False  
1                True             False            False  
2                True             False            False  
3                True             False            False  
4               False              True            False  
...               ...               ...              ...  
4567            False              True            False  
4568            False             False             True  
4569            False              True            False  
4570            False             False            False  
4571            False              True            False  

[4572 rows x 8 columns]

In [162]:
df = df.fillna(df.mean())

In [163]:
df

TV      Radio  Social Media       Sales  Influencer_Macro  \
0     16.0   6.566231      2.907983   54.732757             False   
1     13.0   9.237765      2.409567   46.677897             False   
2     41.0  15.886446      2.913410  150.177829             False   
3     83.0  30.020028      6.922304  298.246340             False   
4     15.0   8.437408      1.405998   56.594181             False   
...    ...        ...           ...         ...               ...   
4567  26.0   4.472360      0.717090   94.685866             False   
4568  71.0  20.610685      6.545573  249.101915             False   
4569  44.0  19.800072      5.096192  163.631457             False   
4570  71.0  17.534640      1.940873  253.610411              True   
4571  42.0  15.966688      5.046548  148.202414             False   

      Influencer_Mega  Influencer_Micro  Influencer_Nano  
0                True             False            False  
1                True             False            False  
2                True             False            False  
3                True             False            False  
4               False              True            False  
...               ...               ...              ...  
4567            False              True            False  
4568            False             False             True  
4569            False              True            False  
4570            False             False            False  
4571            False              True            False  

[4572 rows x 8 columns]

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   TV                4572 non-null   float64
 1   Radio             4572 non-null   float64
 2   Social Media      4572 non-null   float64
 3   Sales             4572 non-null   float64
 4   Influencer_Macro  4572 non-null   bool   
 5   Influencer_Mega   4572 non-null   bool   
 6   Influencer_Micro  4572 non-null   bool   
 7   Influencer_Nano   4572 non-null   bool   
dtypes: bool(4), float64(4)
memory usage: 160.9 KB


In [165]:
df.corr()

TV     Radio  Social Media     Sales  \
TV                1.000000  0.866885      0.527010  0.996652   
Radio             0.866885  1.000000      0.606793  0.867369   
Social Media      0.527010  0.606793      1.000000  0.528121   
Sales             0.996652  0.867369      0.528121  1.000000   
Influencer_Macro  0.021335  0.009518      0.011631  0.019267   
Influencer_Mega  -0.012630 -0.005071      0.013072 -0.011701   
Influencer_Micro -0.004863  0.004212     -0.013312 -0.004099   
Influencer_Nano  -0.003645 -0.008601     -0.011351 -0.003289   

                  Influencer_Macro  Influencer_Mega  Influencer_Micro  \
TV                        0.021335        -0.012630         -0.004863   
Radio                     0.009518        -0.005071          0.004212   
Social Media              0.011631         0.013072         -0.013312   
Sales                     0.019267        -0.011701         -0.004099   
Influencer_Macro          1.000000        -0.332131         -0.331171   
Influencer_Mega          -0.332131         1.000000         -0.338211   
Influencer_Micro         -0.331171        -0.338211          1.000000   
Influencer_Nano          -0.328482        -0.335465         -0.334495   

                  Influencer_Nano  
TV                      -0.003645  
Radio                   -0.008601  
Social Media            -0.011351  
Sales                   -0.003289  
Influencer_Macro        -0.328482  
Influencer_Mega         -0.335465  
Influencer_Micro        -0.334495  
Influencer_Nano          1.000000

In [166]:
df.columns

Index(['TV', 'Radio', 'Social Media', 'Sales', 'Influencer_Macro',
       'Influencer_Mega', 'Influencer_Micro', 'Influencer_Nano'],
      dtype='object')

In [167]:
X = df[['TV', 'Radio', 'Social Media', 'Influencer_Macro', 'Influencer_Mega', 'Influencer_Micro', 'Influencer_Nano']]
X

TV      Radio  Social Media  Influencer_Macro  Influencer_Mega  \
0     16.0   6.566231      2.907983             False             True   
1     13.0   9.237765      2.409567             False             True   
2     41.0  15.886446      2.913410             False             True   
3     83.0  30.020028      6.922304             False             True   
4     15.0   8.437408      1.405998             False            False   
...    ...        ...           ...               ...              ...   
4567  26.0   4.472360      0.717090             False            False   
4568  71.0  20.610685      6.545573             False            False   
4569  44.0  19.800072      5.096192             False            False   
4570  71.0  17.534640      1.940873              True            False   
4571  42.0  15.966688      5.046548             False            False   

      Influencer_Micro  Influencer_Nano  
0                False            False  
1                False            False  
2                False            False  
3                False            False  
4                 True            False  
...                ...              ...  
4567              True            False  
4568             False             True  
4569              True            False  
4570             False            False  
4571              True            False  

[4572 rows x 7 columns]

In [168]:
y = df['Sales']
y

0        54.732757
1        46.677897
2       150.177829
3       298.246340
4        56.594181
           ...    
4567     94.685866
4568    249.101915
4569    163.631457
4570    253.610411
4571    148.202414
Name: Sales, Length: 4572, dtype: float64

In [169]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.33, random_state=0)

In [170]:
X_train.shape, y_train.shape

((3063, 7), (3063,))

In [171]:
X_test.shape, y_test.shape

((1509, 7), (1509,))

In [172]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_processed = scaler.fit_transform(X_train)
X_test_processed = scaler.transform(X_test)
scaler.mean_[0]

54.173577723283785

array([54.28710452, 18.22554312,  3.37820818,  0.25008162,  0.2546523 ,
        0.24877571,  0.24649037])

In [ ]:
scaler.scale_

array([26.12002075,  9.69360437,  2.21173264,  0.43305981,  0.43566559,
        0.43230355,  0.43096736])

In [ ]:
X_train_processed

array([[ 0.79298924,  0.76848587, -0.44469552, ..., -0.58451323,
        -0.57546535, -0.57194672],
       [-0.20241579, -0.4506756 , -1.45955924, ..., -0.58451323,
        -0.57546535,  1.74841461],
       [ 1.13755252,  1.14049349,  0.36357846, ..., -0.58451323,
         1.7377241 , -0.57194672],
       ...,
       [ 1.0609829 ,  0.68898779,  0.3146907 , ..., -0.58451323,
         1.7377241 , -0.57194672],
       [ 1.4821158 ,  0.49335264,  0.47386763, ..., -0.58451323,
         1.7377241 , -0.57194672],
       [ 0.56328039,  0.5921184 ,  0.50457392, ..., -0.58451323,
         1.7377241 , -0.57194672]])

In [ ]:
X_test_processed

array([[-1.08296639, -1.75447528, -0.95299236, ..., -0.58451323,
         1.7377241 , -0.57194672],
       [ 0.29528673, -0.33792921, -1.40331492, ..., -0.58451323,
        -0.57546535, -0.57194672],
       [-0.96811196, -0.8096354 , -1.49937847, ...,  1.71082526,
        -0.57546535, -0.57194672],
       ...,
       [-1.1212512 , -1.29035894, -1.47022138, ..., -0.58451323,
         1.7377241 , -0.57194672],
       [ 1.52040061,  1.05245606,  0.38933602, ..., -0.58451323,
         1.7377241 , -0.57194672],
       [-1.19782081, -0.3420191 , -0.05928603, ...,  1.71082526,
        -0.57546535, -0.57194672]])

In [ ]:
N_train = X_train_processed.shape[0]

In [ ]:
X_train_processed[:5]

array([[ 0.79298924,  0.76848587, -0.44469552,  1.73167391, -0.58451323,
        -0.57546535, -0.57194672],
       [-0.20241579, -0.4506756 , -1.45955924, -0.57747593, -0.58451323,
        -0.57546535,  1.74841461],
       [ 1.13755252,  1.14049349,  0.36357846, -0.57747593, -0.58451323,
         1.7377241 , -0.57194672],
       [-1.50409928, -1.5327525 , -1.15785329, -0.57747593, -0.58451323,
         1.7377241 , -0.57194672],
       [-1.23610562, -0.85228452,  0.75398251, -0.57747593, -0.58451323,
        -0.57546535,  1.74841461]])

In [ ]:
X_train_processed = np.hstack((np.ones((N_train, 1)), X_train_processed))

In [ ]:
X_train_processed[:5]

array([[ 1.        ,  0.79298924,  0.76848587, -0.44469552,  1.73167391,
        -0.58451323, -0.57546535, -0.57194672],
       [ 1.        , -0.20241579, -0.4506756 , -1.45955924, -0.57747593,
        -0.58451323, -0.57546535,  1.74841461],
       [ 1.        ,  1.13755252,  1.14049349,  0.36357846, -0.57747593,
        -0.58451323,  1.7377241 , -0.57194672],
       [ 1.        , -1.50409928, -1.5327525 , -1.15785329, -0.57747593,
        -0.58451323,  1.7377241 , -0.57194672],
       [ 1.        , -1.23610562, -0.85228452,  0.75398251, -0.57747593,
        -0.58451323, -0.57546535,  1.74841461]])

In [ ]:
N_test = X_test_processed.shape[0]

In [ ]:
X_test_processed = np.hstack((np.ones((N_test, 1)), X_test_processed))

In [ ]:
X_test_processed[:5]

array([[ 1.        , -1.08296639, -1.75447528, -0.95299236, -0.57747593,
        -0.58451323,  1.7377241 , -0.57194672],
       [ 1.        ,  0.29528673, -0.33792921, -1.40331492,  1.73167391,
        -0.58451323, -0.57546535, -0.57194672],
       [ 1.        , -0.96811196, -0.8096354 , -1.49937847, -0.57747593,
         1.71082526, -0.57546535, -0.57194672],
       [ 1.        ,  1.44383099,  0.85042988,  1.6696127 , -0.57747593,
        -0.58451323,  1.7377241 , -0.57194672],
       [ 1.        ,  1.71182465,  1.92402722,  1.91722851, -0.57747593,
         1.71082526, -0.57546535, -0.57194672]])

In [ ]:
y_train[:5]

2813    267.179010
1143    173.756497
397     300.753933
1718     52.829001
3483     72.569537
Name: Sales, dtype: float64

In [ ]:
y_train = y_train.to_numpy().reshape(-1, 1)
y_train

array([[267.1790104],
       [173.7564969],
       [300.7539331],
       ...,
       [292.9740224],
       [330.7429786],
       [244.6548065]])

In [ ]:
theta = np.random.randn(X_train_processed.shape[1], 1)
y_pred  = X_train_processed.dot(theta)
y_pred

array([[-1.00755943],
       [ 1.25169501],
       [ 1.29691694],
       ...,
       [ 1.84325219],
       [ 1.64758001],
       [ 2.47459471]])

In [ ]:
class CustomLinearRegression:
  def __init__(self, X_data, y_target, learning_rate =0.01, num_epochs = 10000):
    self.num_samples = X_data.shape[0]
    self.y_target = y_target
    self.learning_rate = learning_rate
    self.num_epochs = num_epochs
    self.X_data = X_data

# Initial weights
    self.theta = np.random.randn(self.X_data.shape[1], 1)
    self.losses = []

# Gradient Descent
  def compute_loss(self, y_pred, y_target):
    loss = np.mean((y_pred - y_target)**2)
    return loss

  def predict(self, X_data):
    y_pred = X_data.dot(self.theta)
    return y_pred

  def fit(self):
    for epoch in range(self.num_epochs):
      y_pred = self.predict(self.X_data)
      loss = self.compute_loss(y_pred, self.y_target)
      self.losses.append(loss)
      gradient_theta = (1/self.num_samples) * 2 * self.X_data.T.dot(y_pred - self.y_target)
      self.theta = self.theta - self.learning_rate * gradient_theta

      if( epoch % 50) == 0:
        print(f'Epoch: {epoch} - Loss : {loss}')
    return {
        'loss ': sum(self.losses)/len(self.losses)
    , 'weight': self.theta}

In [ ]:
linear_model = CustomLinearRegression(X_train_processed, y_train)
linear_model.fit()

Epoch: 0 - Loss : 45836.631970257105
Epoch: 50 - Loss : 5692.900876443266
Epoch: 100 - Loss : 1087.1771585829501
Epoch: 150 - Loss : 387.32556239824555
Epoch: 200 - Loss : 239.3287862084056
Epoch: 250 - Loss : 183.58348970486688
Epoch: 300 - Loss : 150.46555793103082
Epoch: 350 - Loss : 126.89023288585692
Epoch: 400 - Loss : 109.13647002588125
Epoch: 450 - Loss : 95.51355229721491
Epoch: 500 - Loss : 84.98572641426266
Epoch: 550 - Loss : 76.8258830450933
Epoch: 600 - Loss : 70.4934202138627
Epoch: 650 - Loss : 65.5763903996448
Epoch: 700 - Loss : 61.75748990822482
Epoch: 750 - Loss : 58.79115426398358
Epoch: 800 - Loss : 56.48694061651599
Epoch: 850 - Loss : 54.69701800244602
Epoch: 900 - Loss : 53.30658596611907
Epoch: 950 - Loss : 52.22647831329218
Epoch: 1000 - Loss : 51.387433607838666
Epoch: 1050 - Loss : 50.73564989461633
Epoch: 1100 - Loss : 50.229333419416974
Epoch: 1150 - Loss : 49.83601826353084
Epoch: 1200 - Loss : 49.53048441264353
Epoch: 1250 - Loss : 49.2931405537489
Epoc

{'loss ': 163.4666345940307,
 'weight': array([[1.93469053e+02],
        [9.20381393e+01],
        [9.00100117e-01],
        [7.36704652e-02],
        [3.33290286e-01],
        [5.44131210e-01],
        [4.98295188e-01],
        [3.24162618e-01]])}

In [ ]:
preds = linear_model.predict(X_test_processed)

In [ ]:
preds[:5]

array([[ 92.31540805],
       [220.02608418],
       [103.79290785],
       [327.41502119],
       [353.16156034]])

In [ ]:
from sklearn.metrics import r2_score
def r2score(y, y_pred):
  rss = np.sum((y_pred - y)**2)
  tss = np.sum((y - np.mean(y))**2)
  return 1 - (rss/tss)

In [ ]:
r2_score(y_test, preds)

0.9911982841416197

In [ ]:
print(y_test.shape)
print(preds.shape)


(1509,)
(1509, 1)


In [ ]:
r2score(y_test, preds.reshape(-1))

0.9911982841416197

In [ ]:
# Case 1
y_pred = np.array([1 , 2 , 3 , 4 , 5])
y = np.array([1 , 2 , 3 , 4 , 5])
print(r2score(y, y_pred))
# Case 2
y_pred = np.array([1 , 2 , 3 , 4 , 5])
y = np.array([3 , 5 , 5 , 2 , 4])
print(r2score(y, y_pred))

1.0
-2.235294117647059


In [ ]:
# def create_polynomial_features(X, degree =2):
#   X_new = X
#   for i in range(2, degree+1):
#     X_new = np.c_[X_new, np.power(X, i)]
#   return X_new

In [ ]:
# Z = np.array([[1], [2], [3]])

In [ ]:
# create_polynomial_features(Z, 3)

array([[ 1,  1,  1],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [ ]:
def create_polynomial_features(X, degree =2):
  X_mem = []
  for X_sub in X.T:
    X_sub = X_sub.T
    X_new = X_sub
    for d in range(2, degree +1):
      X_new = np.c_[X_sub, np.power(X_sub, d)]
    X_mem.extend(X_new.T)
  return np.c_[X_mem].T

In [ ]:
X = np.array([[1 , 2],
              [2 , 3],
              [3 , 4]])
create_polynomial_features(X, 2)

array([[ 1,  1,  2,  4],
       [ 2,  4,  3,  9],
       [ 3,  9,  4, 16]])

In [ ]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()
linear_model.fit(X_train_processed, y_train)

LinearRegression()

In [ ]:
preds = linear_model.predict(X_test_processed)
r2_score(y_test, preds)

0.9911982841415969

In [ ]:
X_train_processed = X_train_processed[:, 1:]
X_test_processed = X_test_processed[:, 1:]

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train_processed)
X_test_poly = poly.transform(X_test_processed)

In [ ]:
X_train_poly.shape

(3063, 36)

In [ ]:
X_test_poly.shape

(1509, 36)

In [ ]:
X_train_poly = np.hstack((np.ones((N_train, 1)), X_train_poly))

In [ ]:
X_train_poly

array([[ 1.        ,  1.        ,  0.79298924, ...,  0.33116037,
         0.32913552,  0.32712305],
       [ 1.        ,  1.        , -0.20241579, ...,  0.33116037,
        -1.00615202,  3.05695364],
       [ 1.        ,  1.        ,  1.13755252, ...,  3.01968504,
        -0.9938856 ,  0.32712305],
       ...,
       [ 1.        ,  1.        ,  1.0609829 , ...,  3.01968504,
        -0.9938856 ,  0.32712305],
       [ 1.        ,  1.        ,  1.4821158 , ...,  3.01968504,
        -0.9938856 ,  0.32712305],
       [ 1.        ,  1.        ,  0.56328039, ...,  3.01968504,
        -0.9938856 ,  0.32712305]])

In [ ]:
X_test_poly = np.hstack((np.ones((N_test, 1)), X_test_poly))
X_test_poly

array([[ 1.        ,  1.        , -1.08296639, ...,  3.01968504,
        -0.9938856 ,  0.32712305],
       [ 1.        ,  1.        ,  0.29528673, ...,  0.33116037,
         0.32913552,  0.32712305],
       [ 1.        ,  1.        , -0.96811196, ...,  0.33116037,
         0.32913552,  0.32712305],
       ...,
       [ 1.        ,  1.        , -1.1212512 , ...,  3.01968504,
        -0.9938856 ,  0.32712305],
       [ 1.        ,  1.        ,  1.52040061, ...,  3.01968504,
        -0.9938856 ,  0.32712305],
       [ 1.        ,  1.        , -1.19782081, ...,  0.33116037,
         0.32913552,  0.32712305]])

In [ ]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()
linear_model.fit(X_train_poly, y_train)

LinearRegression()

In [ ]:
preds = linear_model.predict(X_test_poly)
r2_score(y_test, preds)

0.9908448238751105